Allow Rails 7.2
mvz/non-digest-assets pull request #88
Opened 2024-05-25 15:23 UTC by texpert

Add `7-2-stable` Rails branch to the CI

2024-05-26 17:48 UTC, mvz requested changes
Thanks for this @texpert! If you can take care of my comments this should be good to merge.

2024-05-26 17:48 UTC, mvz commented on .github/workflows/ruby.yml
> +        appraisal: [rails_6_0, rails_6_1, rails_7_0, rails_7_1, rails_7_2]
From the test failures, it looks like rails 7.2 will not support Ruby 3.0. Can you please exclude that combination from the matrix?

2024-05-26 17:48 UTC, mvz commented on non-digest-assets.gemspec
> +  spec.add_dependency "activesupport", [">= 6.0", "<= 7.2"]
This will exclude activesupport 7.2.1 and up. Please change it to `< 7.3`.

2024-05-26 17:48 UTC, mvz commented on non-digest-assets.gemspec
> +  spec.add_development_dependency "rails", [">= 6.0", "<= 7.2"]
This will exclude rails 7.2.1 and up. Please change it to `< 7.3`.

2024-05-26 17:48 UTC, mvz commented on gemfiles/rails_7_2.gemfile
> +gem "rails", git: 'https://github.com/rails/rails', branch: '7-2-stable'
Please fix the RuboCop offenses on this line.

2024-05-26 20:43 UTC, texpert commented
> Thanks for this @texpert! If you can take care of my comments this should be good to merge.

Thanks for review, @mvz! I have addressed all the comments.

2024-05-27 05:56 UTC, mvz approved these changes

2024-05-27 05:57 UTC, merged

2024-05-27 05:57 UTC, mvz commented
Thanks again, @texpert!

2024-05-27 07:27 UTC, texpert commented
Thanks for help, @mvz!

Can you, please, craft a new release?!

2024-08-30 06:20 UTC, mvz commented
Hi @texpert I just released version 2.4.0 which includes this change.